# Generated by Django 4.1.7 on 2023-03-29 13:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("company", "0003_alter_worker_position"),
    ]

    operations = [
        migrations.AddField(
            model_name="worker",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
